import React, { useState } from "react";

export default function App() {
  const menu = [
      { id: 1, name: "Espresso", category: "Coffee", price: 20000, img: "https://images.unsplash.com/photo-1580910051072-4d36474e4f29?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8ZXNwcmVzc298fDB8fHx8MTY5MzAxMjM4OA&ixlib=rb-4.0.3&q=80&w=400" },
          { id: 2, name: "Cappuccino", category: "Coffee", price: 25000, img: "https://images.unsplash.com/photo-1601924582975-041e1d5c0027?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8Y2FwcHVjY2lub3x8MHx8fHwxNjkzMDEyNDE5&ixlib=rb-4.0.3&q=80&w=400" },
              { id: 3, name: "Latte", category: "Coffee", price: 30000, img: "https://images.unsplash.com/photo-1614850523543-f06b5e4d935b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8bGF0dGV8fDB8fHx8MTY5MzAxMjQyOA&ixlib=rb-4.0.3&q=80&w=400" },
                  { id: 4, name: "Mocha", category: "Coffee", price: 35000, img: "https://images.unsplash.com/photo-1511920170033-f8396924c348?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8bW9jaGF8fDB8fHx8MTY5MzAxMjQ1NQ&ixlib=rb-4.0.3&q=80&w=400" },
                      { id: 5, name: "Americano", category: "Coffee", price: 22000, img: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8YW1lcmljYW5vfHwwfHx8fDE2OTMwMTI0ODU&ixlib=rb-4.0.3&q=80&w=400" },
                          { id: 6, name: "Croissant", category: "Snack", price: 15000, img: "https://images.unsplash.com/photo-1598485799753-b7f07ab5474c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8Y3JvaXNzYW50fHwwfHx8fDE2OTMwMTI1MTc&ixlib=rb-4.0.3&q=80&w=400" },
                              { id: 7, name: "Donut", category: "Snack", price: 12000, img: "https://images.unsplash.com/photo-1616488164763-0c7f773f03b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8ZG9udXR8fDB8fHx8MTY5MzAxMjUzNw&ixlib=rb-4.0.3&q=80&w=400" },
                                  { id: 8, name: "Brownie", category: "Snack", price: 18000, img: "https://images.unsplash.com/photo-1599785209790-d19a0a8f9e0f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8YnJvd25pZXx8MHx8fHwxNjkzMDEyNTYw&ixlib=rb-4.0.3&q=80&w=400" },
                                      { id: 9, name: "Sandwich", category: "Snack", price: 25000, img: "https://images.unsplash.com/photo-1601924582975-041e1d5c0027?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8c2FuZHdpY2h8fDB8fHx8MTY5MzAxMjU4NQ&ixlib=rb-4.0.3&q=80&w=400" },
                                        ];

                                          const [cart, setCart] = useState([]);
                                            const [filter, setFilter] = useState("All");
                                              const [search, setSearch] = useState("");

                                                const filteredMenu = menu
                                                    .filter(item => filter === "All" || item.category === filter)
                                                        .filter(item => item.name.toLowerCase().includes(search.toLowerCase()));

                                                          const addToCart = (item) => {
                                                              const exist = cart.find(i => i.id === item.id);
                                                                  if (exist) {
                                                                        setCart(cart.map(i => i.id === item.id ? { ...i, qty: i.qty + 1 } : i));
                                                                            } else {
                                                                                  setCart([...cart, { ...item, qty: 1 }]);
                                                                                      }
                                                                                        };

                                                                                          const removeFromCart = (id) => setCart(cart.filter(i => i.id !== id));
                                                                                            const incrementQty = (id) => setCart(cart.map(i => i.id === id ? { ...i, qty: i.qty + 1 } : i));
                                                                                              const decrementQty = (id) => setCart(cart.map(i => i.id === id ? { ...i, qty: Math.max(i.qty - 1, 1) } : i));

                                                                                                const total = cart.reduce((sum, i) => sum + i.price * i.qty, 0);

                                                                                                  const getWA = () => {
                                                                                                      if (cart.length === 0) return "#";
                                                                                                          let message = "Halo, saya ingin memesan:\n";
                                                                                                              cart.forEach(item => {
                                                                                                                    message += `${item.name} x${item.qty} = Rp ${(item.price * item.qty).toLocaleString()}\n`;
                                                                                                                        });
                                                                                                                            message += `Total: Rp ${total.toLocaleString()}`;
                                                                                                                                return `https://wa.me/?text=${encodeURIComponent(message)}`;
                                                                                                                                  };

                                                                                                                                    return (
                                                                                                                                        <div className="min-h-screen bg-gradient-to-br from-yellow-50 via-yellow-100 to-white p-6 font-sans">
                                                                                                                                              <h1 className="text-4xl font-bold text-center mb-2">☕ Coffee & Snack Shop</h1>
                                                                                                                                                    <p className="text-center text-gray-600 mb-6">Hari ini, pilih menu favoritmu!</p>

                                                                                                                                                          {/* Search & Filter */}
                                                                                                                                                                <div className="flex flex-col md:flex-row justify-center gap-4 mb-6 items-center">
                                                                                                                                                                        <input
                                                                                                                                                                                  type="text"
                                                                                                                                                                                            placeholder="Search menu..."
                                                                                                                                                                                                      value={search}
                                                                                                                                                                                                                onChange={(e) => setSearch(e.target.value)}
                                                                                                                                                                                                                          className="px-4 py-2 rounded border w-full md:w-1/3 focus:outline-none focus:ring-2 focus:ring-green-500"
                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                          <div className="flex gap-2">
                                                                                                                                                                                                                                                    {["All", "Coffee", "Snack"].map(cat => (
                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                              key={cat}
                                                                                                                                                                                                                                                                                            onClick={() => setFilter(cat)}
                                                                                                                                                                                                                                                                                                          className={`px-4 py-2 rounded ${
                                                                                                                                                                                                                                                                                                                          filter === cat ? "bg-green-500 text-white" : "bg-gray-200 text-gray-700 hover:bg-gray-300"
                                                                                                                                                                                                                                                                                                                                        }`}
                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                  {cat}
                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                            {/* Menu Grid */}
                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                                                                                                                                                                                                                                                                                                                                                                                                          {filteredMenu.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="bg-white p-4 rounded-xl shadow-md hover:scale-105 transform transition duration-300"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src={item.img} alt={item.name} className="w-full h-32 object-cover rounded mb-3"/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2 className="text-xl font-semibold">{item.name}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-600">{item.category} - Rp {item.price.toLocaleString()}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => addToCart(item)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="mt-3 w-full bg-green-500 text-white py-2 rounded hover:bg-green-600 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Add to Cart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Cart */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-10 bg-white p-6 rounded-xl shadow-md">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-2xl font-bold mb-4">🛒 Your Cart</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {cart.length === 0 && <p>Your cart is empty</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {cart.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={item.id} className="flex justify-between items-center mb-2 flex-wrap gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2 flex-wrap">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>{item.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => decrementQty(item.id)} className="bg-gray-200 px-2 rounded hover:bg-gray-300">-</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>{item.qty}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => incrementQty(item.id)} className="bg-gray-200 px-2 rounded hover:bg-gray-300">+</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Rp {(item.price * item.qty).toLocaleString()}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => removeFromCart(item.id)} className="text-red-500 hover:text-red-700">Remove</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {cart.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-4 flex flex-col md:flex-row justify-between items-center font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>Total: Rp {total.toLocaleString()}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href={getWA()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="mt-2 md:mt-0 bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Checkout via WhatsApp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }